### ISSUE TITLE
Use a namespace for environment variables?

### ISSUE THREAD

**Issue by tripleee** [bertrand-benoit/scripts-common#2]
Your utilities should probably define their own namespace so you don't clobber any `VERBOSE` or etc variable names required by other utilities. You'll notice how e.g. Bash defines most of its own variables with a `BASH_` prefix, although this is not entirely consistent.

**Comment by bertrand-benoit** [comment]
Yes it is a good idea, I though about it without taking a decision yet.
I think something like `SCRIPTS-COMMON-VERBOSE` would be far too long, and something like `_VERBOSE` may still be too ambiguous.
Do you have any idea? ^^

**Comment by tripleee** [comment]
Can't have a dash in the name and I agree the first is too long anyway. Something like `BBSC_` (Bertrand Benoit's Scripts-Common) should hopefully be reasonably unique. Probably google to check that it doesn't happen to be used by some popular package. Quick check reveals no hits for `BBSC_VERBOSE`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bertrand-benoit** [comment]
Hey @tripleee, I finally found the time to work on this issue, and just completed it (it is now hosted on Gitlab) => https://gitlab.com/bertrand-benoit/scripts-common/-/merge_requests/12/diffs

As soon as I complete the documentation, I will release the version 2.1.

Can I count on you to speak about the tool to 1/ help people finding it   2/ allow me to get feebacks and keep on improving the tool ?
